# Generated by Django 5.1.6 on 2025-02-19 10:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("event_manager", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.ManyToManyField(
                related_name="event_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
