# Generated by Django 5.1.6 on 2025-02-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event_manager", "0003_event_members"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "events",
                    models.ManyToManyField(
                        related_name="event_handler", to="event_manager.event"
                    ),
                ),
            ],
        ),
    ]
