# Generated by Django 5.1.6 on 2025-02-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event_manager", "0004_eventhandler"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventHandler",
        ),
    ]
